### ISSUE TITLE
Hi,please help me.

### ISSUE THREAD

**Issue by ZzzTD** [Yijunmaverick/UniversalStyleTransfer#16]
May I ask how to generate the Inverting white features for Figure 2,thanks a lot！
![image](https://github.com/Yijunmaverick/UniversalStyleTransfer/assets/58813118/5e9c1c00-f28f-479a-84b3-be487464f36e)

**Comment by Yijunmaverick** [comment]
Thanks for your interest.

By just applying the whitening step and removing the coloring step, i.e., feeding the whitened feature directly into the decoder, you will obtain the above results.

**Comment by ZzzTD** [comment]
Thank you for your reply
