### ISSUE TITLE
License

### ISSUE THREAD

**Issue by backnotprop** [Yijunmaverick/UniversalStyleTransfer#7]
Is there a license for this software?

**Comment by Yijunmaverick** [comment]
@mdramos Thanks for the reminder. I just add a MIT license. Generally, I want it to be simple.

**Comment by backnotprop** [comment]
@Yijunmaverick thanks, though I see in the README this line:

> Torch implementation of our NIPS17 paper on universal style transfer. For academic use only.

If the license is MIT, would that negate `For academic use only` ?

**Comment by Yijunmaverick** [comment]
@mdramos :) Oh, you're right. I remove it. Hope it can benefit more works.
